services:
  db:
    image: postgres:17
    container_name: sqlchallenge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenges
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
